### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by tajemouti** [tajemouti/medical-appointments-back-end#10]
## Hi Reviewer 👋 ##

This issue is created to provide task assignments and team information for [Doctor appointment cap project](https://github.com/users/tajemouti/projects/2/views/1).

![image](https://github.com/tajemouti/medical-appointments-back-end/assets/130588108/ff700dde-0bf9-4d9f-9036-27be88479aff)

We have a team of 4 working on this project:

Team member #1: [Shah Zaman](https://github.com/shahzaman900)
Team member #2: [Wonde](https://github.com/wacoo)
Team member #3: [Enrico](https://github.com/Bettenoch)
Team member #4: [Tajemouti](https://github.com/tajemouti)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
